// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModusCreate.NewsFeed.Database;

namespace ModusCreate.NewsFeed.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181207071616_AddFeedEntities")]
    partial class AddFeedEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModusCreate.NewsFeed.Domain.Feed", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description");

                    b.Property<string>("FeedUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("ModusCreate.NewsFeed.Domain.FeedEntry", b =>
                {
                    b.Property<int>("FeedId");

                    b.Property<string>("Id");

                    b.Property<DateTimeOffset>("LastUpdatedTime");

                    b.Property<DateTimeOffset>("PublishDate");

                    b.Property<string>("Summary");

                    b.Property<string>("Title");

                    b.HasKey("FeedId", "Id");

                    b.ToTable("FeedEntries");
                });

            modelBuilder.Entity("ModusCreate.NewsFeed.Domain.FeedSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeedUrl");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("FeedSubscriptions");
                });

            modelBuilder.Entity("ModusCreate.NewsFeed.Domain.Feed", b =>
                {
                    b.HasOne("ModusCreate.NewsFeed.Domain.FeedSubscription")
                        .WithOne("Feed")
                        .HasForeignKey("ModusCreate.NewsFeed.Domain.Feed", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ModusCreate.NewsFeed.Domain.FeedEntry", b =>
                {
                    b.HasOne("ModusCreate.NewsFeed.Domain.Feed")
                        .WithMany("Entries")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
